busterapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login,logout

urlpatterns = [
    url(r'^$', views.home, name = 'home'),
    url(r'^registration/$', views.registration, name = 'registration'),
    url(r'^login/$', login, {'template_name' : 'busterapp/login.jinja'}),
    url(r'^logout/$', logout, {'template_name': 'busterapp/logout.jinja'}),
    url(r'^project/$', views.project, name = 'project'),
    url(r'^project/update_project/(?P<project_id>[0-9]+)/$', views.update_project, name = 'update_project'),
    url(r'^task/$', views.task, name = 'task'),
    url(r'^task/update_task/(?P<task_id>[0-9]+)/$', views.update_task, name = 'update_task'),
    url(r'^signup/$', views.signup, name = 'signup'),
    url(r'^(?P<parent_id>[0-9]+)/taskchild/$', views.taskchild, name = 'taskchild'),
]

taskbuster/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('busterapp.urls')),
]

busterapp/models.py
from django.db import models
from users.models import UserProfile

class Project(models.Model):
	name = models.CharField(max_length=30, )
	added_on = models.DateTimeField(null=True, blank=True, auto_now_add=True)
	updated_on = models.DateTimeField(null=True, blank=True, auto_now=True)
	added_by = models.ForeignKey(UserProfile, null=True, blank=True, on_delete=models.SET_NULL)

	class meta:
		verbose_name = 'Project'
		verbose_name_plural = 'Projects'
		db_table = 'busterapp_project'

	def __str__(self):
		return "%s - %s" %( self.name, self.id )		

class Task(models.Model):
	name = models.CharField(max_length=30, null=True, blank=True)
	parent = models.ForeignKey('self', null=True, blank=True)
	added_on = models.DateTimeField(null=True, blank=True, auto_now_add=True)
	updated_on = models.DateTimeField(null=True, blank=True, auto_now=True)
	added_by = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL )

	class Meta:
		verbose_name = 'Task'
		verbose_name_plural = 'Tasks'
		db_table = 'task'

	def __str__(self):
		return "%s - %s" %( self.name, self.id )

users/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import PermissionsMixin, BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _



class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):
		"""
		Creates and saves a User with the given email and password.
		"""
		if not email:
			raise ValueError('The given email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password=None, **extra_fields):
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_superuser', True)
		extra_fields.setdefault('is_staff', True)

		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, password, **extra_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(_('email address'), unique=True)
	name = models.CharField(_('first name'), max_length=30, blank=True)
	added_on = models.DateTimeField(_('date joined'), auto_now_add=True)
	update_on = models.DateTimeField(_('date updated'), auto_now=True)
	is_active = models.BooleanField(_('active'), default=True)
	avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
	is_staff = models.BooleanField(_('staff status'),default=False)

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	class Meta:
		verbose_name = _('user')
		verbose_name_plural = _('users')
		db_table = 'users'

	def get_full_name(self):
		
		return self.name.strip() if self.name else ''

	def get_short_name(self):

		return self.name
	
	def __str__(self):
		
		return "%s - %s" %(self.email, self.id)

busterapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from users.models import UserProfile
from .models import Project, Task

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email',max_length=254, help_text='Required a valid email address.')
    class Meta:
        model = UserProfile
        fields = ('email', )

class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ('name' , 'added_by') 

class TaskForm(forms.ModelForm):
	class Meta:
		model = Task
		fields = ('name' , 'added_by')	
			
	

busterapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render , redirect , get_object_or_404
from django.http import *
from users.models import UserProfile 
from django.http import HttpResponseRedirect

from .models import Project
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm , ProjectForm , TaskForm
from django.core.urlresolvers import reverse

from django.contrib.auth import authenticate, login
from .models import Project, Task
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login')
def home(request):
    users_data = UserProfile.objects.all()
    projects = Project.objects.filter(added_by = request.user)
    return render(request, 'busterapp/home.jinja', {'users_data' : users_data , 'projects' : projects})

#registration page here
def registration(request):
    form = RegistrationForm()
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/login')
    return render(request, 'busterapp/registration.jinja', { 'form': form})   

#extra branch changes 
@login_required(login_url='/login')
def project(request):
    form = ProjectForm()
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, 'busterapp/project.jinja', { 'form': form , })

#update project comment
@login_required(login_url='/login')
def update_project(request,project_id):
    child = Task.objects.filter(parent=None)
    alltask = Task.objects.all()
    projects = get_object_or_404(Project, id = project_id)
    tasks = Task.objects.filter(added_by = projects)
    form = ProjectForm(request.POST or None, instance = projects)
    if request.method == "POST":
        if form.is_valid():
            form_partial = form.save(commit=False)
            form_partial.added_by = request.user
            form_partial.save()
            return HttpResponseRedirect('/')
    return render (request,'busterapp/project_update.jinja', {'form' : form , 'projects' : projects , 'tasks' : tasks, 'alltask' :  alltask , 'child' : child } )        

# Add One more comment
@login_required(login_url='/login')
def task(request):
    form = TaskForm()
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render (request, 'busterapp/task.jinja' , {'form' : form }) 

@login_required(login_url='/login')
def update_task(request,task_id):
    url_link = reverse('update_task' , kwargs={'task_id': task_id})
    tasks = get_object_or_404(Task, id=task_id)
    childs = Task.objects.filter(parent = tasks)
    task_name = tasks.added_by
    form = TaskForm(request.POST or None, instance = tasks)
    if request.method == "POST":
        if form.is_valid():
            form_partial = form.save(commit=False)
            form_partial.added_by = task_name
            form_partial.save()
            return HttpResponseRedirect(url_link)
    return render (request,'busterapp/task_update.jinja', {'form' : form , 'tasks' : tasks , 'childs' : childs } )   

@login_required(login_url='/login')
def taskchild(request,parent_id):
    url_link = reverse('taskchild' , kwargs={'parent_id': parent_id})
    tasks = get_object_or_404(Task, id=parent_id)
    childs = Task.objects.filter(parent = tasks)
    form = TaskForm(request.POST or None)
    if request.method == "POST":
        form_partial = form.save(commit=False)
        form_partial.parent = tasks
        form_partial.save()
        return HttpResponseRedirect(url_link)
    return render (request,'busterapp/taskchild.jinja', {'form' : form , 'tasks' : tasks, 'childs' : childs  } ) 

users/views.py
from django.shortcuts import render

# Create your views here.

busterapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{%block title%} {%endblock%}</title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% if request.user.is_authenticated %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">TaskBuster</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-user"></span>Hi {{user}}</a></li>
    </ul>
  </div>
</nav>
{% else %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">TaskBuster</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <li><a href="/registration"><span class="glyphicon glyphicon-user"></span> register</a></li>
    </ul>
  </div>
</nav>
{% endif %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 align="center">TaskBuster App</h1> 
  </div>
</div>
</body>
{% block content %}

{% endblock %}
</body>
</html>

busterapp/templates/busterapp/home.jinja
{% extends "base.html" %}

{% block title %} TaskBuster {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
{% if request.user.is_authenticated%}
<div class="container">
  <a href="project" class="btn btn-info" role="button">Add Project</a>
</div>
{% else %}
<div class="container">
  <p>To Add Project You have to login first!!!!</p>
</div>
{% endif %}

<br><br>
<div class="container">
  <table class="table table-bordered">
    <tbody>
    <th> Project Name </th>
    <th> Added_by </th>
    <th> Added_On </th>
      {% for project in projects  %}
      <tr>
          <td>
            <a href="/project/update_project/{{project.id}}">
                 {{ project.name }}
            </a>
          </td>
          <td>
                 {{ project.added_by }}
          </td> 
          <td>
                 {{ project.added_on }}
          </td>
      </tr>
    {% endfor  %}
    </tbody>
  </table>
  
</div>
   {% endblock %}
</body>
</html>

busterapp/templates/busterapp/login.jinja
{% extends "base.html" %}

{% block title %} Login Page {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container" >
     <h2 align="center">Login Page</h2>
     <br><br>
     <form method="POST">
         {% csrf_token %}
         {{form.as_p}}
         <button type="submit" class="btn btn-success">Login</button>
     </form>
 </div>
  {% endblock %}
</body>
</html>

busterapp/templates/busterapp/logout.jinja
{% extends "base.html" %}

{% block title %} Logout Page {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
    <br><br>
    <h2 align="center">Yoh Have Succesfully Logout!</h2>
  {% endblock %}
</body>
</html>

busterapp/templates/busterapp/project.jinja
{% extends "base.html" %}

{% block title %} Project {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container">
     <h2 align="center">Add Project </h2>
     <br><br>
     <form method="POST">
         {% csrf_token %}
         <h4> Project Name : {{form.name}} </h4>
         <h4> Added_by     : {{form.added_by}} </h4>
         <button type="submit" class="btn btn-success">Add</button>
     </form>
 </div>

  {% endblock %}
</body>
</html>

busterapp/templates/busterapp/project_update.jinja
{% extends "base.html" %}

{% block title %} Project Update {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container">
     <h2 align="center">Update Project </h2>
     <br><br>
     <form method="POST">
         {% csrf_token %}
         <h4> Project Name : {{form.name}} </h4>

         <button type="submit" class="btn btn-success">Update</button>
     </form>
 </div>
 <div class="container">
     <br>
     <h4 align="center"> <a href="/task" class="btn btn-info" role="button">Add Task Here</a></h4>
     </form>
 </div>
 <br><br>
<div class="container">
    <ul>
        {% for task in tasks recursive %}
            <li>
                <a href="/task/update_task/{{task.id}}">
                 {{ task.name }} -  {{ task.added_on }}
                </a>
                {% if task.task_set.all() %}
                    <ul>{{ loop(task.task_set.all()) }}</ul>
                {% endif %}
            </li>
        {% endfor  %}
    </ul>
<br>
</div>
{% endblock %}
</body>
</html>

busterapp/templates/busterapp/registration.jinja
{% extends "base.html" %}

{% block title %} Registration {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container">
     <h2 align="center">Registration Form </h2>
     <br><br>
     <form method="POST" class="post-form">
         {% csrf_token %}
         {{form.as_p}}
         <h4 align="center"> <button type="submit" class="btn btn-success">Register</button></h4>
     </form>
 </div>
  {% endblock %}
</body>
</html>

busterapp/templates/busterapp/signup.jinja
{% extends "base.html" %}

{% block title %} Sign Up Form {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
<div class="container">
  <form method="POST">
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
    </div>
    <div class="form-group">
      <label for="pwd">Confirm Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Re-enter password" name="pswd1">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}
</body>
</html>

busterapp/templates/busterapp/task.jinja
{% extends "base.html" %}

{% block title %} Task {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container">
     <h2 align="center">Add Task </h2>
     <br><br>
     <form method="POST">
         {% csrf_token %}
         <h4> Task Name : {{form.name}} </h4>
         <h4> Added_by  : {{form.added_by}} </h4>
         <button type="submit" class="btn btn-success">Add</button>
     </form>
 </div>
  {% endblock %}
</body>
</html>

busterapp/templates/busterapp/task_update.jinja
{% extends "base.html" %}

{% block title %} Project Update {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container">
     <h2 align="center">Update Task </h2>
     <br><br>
     <form method="POST">
         {% csrf_token %}
         <h4> Task Name : {{form.name}} </h4>
         <button type="submit" class="btn btn-success">Update</button>
     </form>
 </div>
 <br>
 <div class="container">
  <h4 align="center"><a href="/{{tasks.id}}/taskchild/" class="btn btn-info" role="button">Add Child task</a></h4>
<br>
<hr>
<div class="container">
    <p>Parent Task: {{ tasks.name}}</p>
    {%for child in childs %}
    <p> Child Task: <a href = "/{{child.id}}/taskchild/">{{child.name}}</a></p>
    {% endfor %}
 </div>
  {% endblock %}
   
   
</body>
</html>

busterapp/templates/busterapp/taskchild.jinja
{% extends "base.html" %}

{% block title %} ChildTask {% endblock %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
   {% block content %}
  <div class="container">
     <h2 align="center">Add Task Child</h2>
     <br><br>
     <form method="POST">
         {% csrf_token %}
         <h4> Task Name : {{form.name}} </h4>
         <button type="submit" class="btn btn-success">Add</button>
     </form>
 </div>
 <br>
 <hr>
 <div class="container">
    <p>Parent Task: {{ tasks.name}}</p>
    {%for child in childs %}
    <p> Child Task:<a href = "/{{child.id}}/taskchild/">{{child.name}}</a></p>
    {% endfor %}
 </div>
  {% endblock %}
</body>
</html>

busterapp/templates/busterapp/tasklist.jinja
{% extends "base.html" %}

{% block title %} ChildTask List {% endblock %}
<!DOCTYPE html>

<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
<div class="container">
{% for tasklist in taskchilds %}
  <p>Task Name : {{tasklist.name}}</p>
  <p>Child Task: {{tasklist.added_by}}</p>
  <hr>
{% endfor %}
</div>

   {% endblock %}
</body>
</html>